### ISSUE TITLE
doesn't post updates to files in subfolders

### ISSUE THREAD

**Issue by brandoncurtis** [optionfactory/gdrive2slack#12] opened 2015-09-25 20:15 UTC
I am using on gdrive2slack with multiple Google Accounts and Slack channels.  In most of these installations it notices updates in subfolders and publishes them to Slack, but in a few cases it ignores some or all subfolder activity.

**Comment by teddyboar** [comment] 2016-02-11 10:17
Duplicate of #11, should be fixed, let us know if the problem persists by opening another ticket

**Closed by teddyboar** 2016-02-11 10:17 UTC
